#!/bin/bash

### BEGIN INIT INFO
# Provides:          influx-nats-relay
# Required-Start:    $remote_fs
# Required-Stop:     $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Influx NATS Relay
# Description:       Influx NATS Relay
### END INIT INFO

source /etc/default/influx-nats-relay;

DAEMON="/usr/bin/influx-nats-relay";
PIDFILE="/var/run/influx-nats-relay.pid";

usage() {
  echo "$0 {start|stop|restart|status}";
}

## Support Functions ##

daemon_running() {
  [[ -f "$PIDFILE" ]] &&
  ps -p "$(daemon_pid)" 2>&1 > /dev/null &&
  echo "Daemon running ($(daemon_pid))" &&
  return 0;
  return 1;
}

daemon_pid() {
  cat $PIDFILE;
}

## Init Functions ##

start() {
  daemon_running && echo "Daemon alreading running on PID $(daemon_pid)" && exit 1;
  export PIDFILE
  start-stop-daemon -b -m --start --pidfile $PIDFILE --exec $DAEMON -- $OPTS;
}

stop() {
  start-stop-daemon --stop --pidfile $PIDFILE $DAEMON --retry 5;
}

restart() {
  $0 stop;
  $0 start;
}

status() {
  daemon_running && echo "Daemon running on PID $(daemon_pid)" && exit 0;
  daemon_running || { echo "Daemon is dead" && exit 3 ; };
}

case "$1" in
  "start")    start   ;;
  "stop")     stop    ;;
  "restart")  restart ;;
  "status")   status  ;;
  "console")  console ;;
  *)          usage   ;;
esac;

exit 0;
